language: node_js
arch:
  - amd64
  - ppc64le
os: linux
node_js:
  - node
  - lts/*
install:
  - cd GA
  - npm install
  - node googleAnalytics.js
  - npm install validator
  - npm install concatenate-files
